[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmd = 'bun install'

[phases.build]
cmd = 'bun run build'

[start]
cmd = 'bun .output/server/index.mjs'

[variables]
NODE_ENV = 'production'
NITRO_BUILDER = 'rolldown'
