[phases.build]
cmds = ['pnpm install', 'pnpm build']

[start]
cmd = 'node .output/server/index.mjs'

[variables]
NODE_ENV = 'production'
NIXPACKS_NODE_VERSION = '22'
npm_config_supportedArchitectures_os = 'linux'
npm_config_supportedArchitectures_cpu = 'x64'
